const UploadedDocmentModel = [
  {
    Sno: 1,
    SerialNo: 30,
    vKey: "220225094519-00002",
    FileName: "220225094519-00002-22022025144647-1.docx",
    ActualFileName: "Types of Blocking(10)(2).docx",
    DocTypeKey: 1,
    DocTypeTitle: "POSSESSION LETTER",
    AppliedBy: "1",
  },
  {
    Sno: 2,
    SerialNo: 31,
    vKey: "220225094519-00002",
    FileName: "220225094519-00002-22022025144647-2.pdf",
    ActualFileName: "DESIGN WING DOCUMENTS-3-1.pdf",
    DocTypeKey: 2,
    DocTypeTitle: "ALLOTMENT LETTER",
    AppliedBy: "1",
  },
  {
    Sno: 3,
    SerialNo: 32,
    vKey: "220225094519-00002",
    FileName: "220225094519-00002-22022025144647-3.docx",
    ActualFileName: "Types of Blocking(12).docx",
    DocTypeKey: 3,
    DocTypeTitle: "N.O.C FOR CONSTRUCTION",
    AppliedBy: "1",
  },
  {
    Sno: 4,
    SerialNo: 33,
    vKey: "220225094519-00002",
    FileName: "220225094519-00002-22022025144647-4.docx",
    ActualFileName: "LHC-08286-13022025145045-1.docx",
    DocTypeKey: 4,
    DocTypeTitle: "OWNER VALID CNIC",
    AppliedBy: "1",
  },
  {
    Sno: 5,
    SerialNo: 34,
    vKey: "220225094519-00002",
    FileName: "220225094519-00002-22022025144647-5.pdf",
    ActualFileName: "DESIGN WING DOCUMENTS-3-1.pdf",
    DocTypeKey: 4,
    DocTypeTitle: "OWNER VALID CNIC",
    AppliedBy: "1",
  },
];

const structuralWorkInfo = [
  {
    id: 1,
    userId: 1,
    vkey: "123143243-3123",
    userName: "Btl Final",
    registrationNumber: "BNL-02351",
    name: "Bilal Ahmed",
    cnic: "35201-1234567-1",
    email: "bilal.ahmed@example.com",
    contactNumber: "0300-1234567",
    plotSize: "10 Marla",
    plotCategory: "Residential",
    block: "Block A",
    lessArea: "0",
    ExessArea: "0",
    sector: "Sector 1",
    plotType: "Corner",
    plotNo: "A-101",
    totalArea: "2250 sq ft",
    optionalFeatures: ["Basement", "Terrace"],
    ad: "Standard Plan - 2024",
    designType: "Modern",
    NOCIssueDate: "2024-02-15",
    NOCExpiryDate: "2025-02-15",
    PossessionIssueDate: "2024-03-01",
    PossessionExpiryDate: "2025-03-01",
    FileStatusTitle: "Active",
    architectName: 1,
    scheduleDate: "2025-05-01",
    scheduleTime: "10:00",
  },
  {
    id: 2,
    userId: 2,
    vkey: "872364875-1462",
    userName: "Final Test",
    registrationNumber: "BNL-02352",
    name: "Ayesha Tariq",
    cnic: "35202-2345678-2",
    email: "ayesha.tariq@example.com",
    contactNumber: "0321-9876543",
    ExessArea: "0",
    lessArea: "0",

    plotSize: "5 Marla",
    plotCategory: "Commercial",
    block: "Block B",
    sector: "Sector 2",
    plotType: "Standard",
    plotNo: "B-202",
    totalArea: "1125 sq ft",
    optionalFeatures: ["Frame Structure"],
    ad: "Commercial Launch",
    designType: "Contemporary",
    NOCIssueDate: "2024-01-10",
    NOCExpiryDate: "2025-01-10",
    PossessionIssueDate: "2024-02-01",
    PossessionExpiryDate: "2025-02-01",
    FileStatusTitle: "Pending",
    architectName: 2,
    scheduleDate: "2025-05-02",
    scheduleTime: "11:30",
  },
  {
    id: 3,
    vkey: "672348678-2784",
    userName: "Test User",
    registrationNumber: "BNL-02353",
    name: "Usman Riaz",
    cnic: "35203-3456789-3",
    email: "usman.riaz@example.com",
    ExessArea: "0",
    lessArea: "0",
    userId: 3,
    contactNumber: "0333-7654321",
    plotSize: "1 Kanal",
    plotCategory: "Residential",
    block: "Block C",
    sector: "Sector 3",
    plotType: "Park Facing",
    plotNo: "C-303",
    totalArea: "4500 sq ft",
    optionalFeatures: ["Swimming Pool", "Solar Panels"],
    ad: "Premium Package",
    designType: "Spanish",
    NOCIssueDate: "2023-11-20",
    NOCExpiryDate: "2024-11-20",
    PossessionIssueDate: "2023-12-05",
    PossessionExpiryDate: "2024-12-05",
    FileStatusTitle: "Approved",
    architectName: 3,
    scheduleDate: "2025-05-03",
    scheduleTime: "02:00",
  },
  {
    id: 4,
    userId: 4,
    vkey: "567834234-9432",
    userName: "DW user",
    registrationNumber: "BNL-02354",
    name: "Ali Khan",
    cnic: "35204-4567890-4",
    email: "ali.khan@example.com",
    contactNumber: "0345-6789012",
    ExessArea: "0",
    lessArea: "0",
    plotSize: "7 Marla",
    plotCategory: "Residential",
    block: "Block D",
    sector: "Sector 4",
    plotType: "Standard",
    plotNo: "D-404",
    totalArea: "1575 sq ft",
    optionalFeatures: ["Basement"],
    ad: "Basic Plan",
    designType: "Classic",
    NOCIssueDate: "2024-04-01",
    NOCExpiryDate: "2025-04-01",
    PossessionIssueDate: "2024-04-15",
    PossessionExpiryDate: "2025-04-15",
    FileStatusTitle: "Expired",
    architectName: 1,
    scheduleDate: "2025-05-04",
    scheduleTime: "09:00",
  },
  {
    id: 5,
    userId: 5,
    vkey: "934875342-7689",
    userName: "DW Employee",
    registrationNumber: "BNL-02355",
    name: "Sana Malik",
    cnic: "35205-5678901-5",
    email: "sana.malik@example.com",
    contactNumber: "0312-3456789",
    plotSize: "12 Marla",
    ExessArea: "0",
    lessArea: "0",
    plotCategory: "Residential",
    block: "Block E",
    sector: "Sector 5",
    plotType: "Corner",
    plotNo: "E-505",
    totalArea: "2700 sq ft",
    optionalFeatures: ["Rooftop Garden"],
    ad: "Employee Special Offer",
    designType: "Minimalist",
    NOCIssueDate: "2023-08-01",
    NOCExpiryDate: "2024-08-01",
    PossessionIssueDate: "2023-08-15",
    PossessionExpiryDate: "2024-08-15",
    FileStatusTitle: "Inactive",
    architectName: 5,
    scheduleDate: "2025-05-05",
    scheduleTime: "12:15",
  },
];

const structuralStatus = [
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Acknowledged",
    Value: 19,
  },
  { disabled: false, group: null, selected: false, Text: "Reject", Value: 20 },
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Complete",
    Value: 21,
  },
];

const plotapprovel = [
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Pending",
    Value: 10,
  },
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Received",
    Value: 23,
  },
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Verified",
    Value: 4,
  },
];

const preparedrawing = [
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Verified",
    Value: 4,
  },
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Drawing Preparing ",
    Value: 24,
  },
];

const issuancedrawing = [
   {
    disabled: false,
    group: null,
    selected: false,
    Text: "Verified",
    Value: 4,
  },
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Drawing Preparing ",
    Value: 24,
  },
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Drawing Issuance",
    Value: 25,
  },
];

const LDAStatus = [
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Pending",
    Value: 10,
  },
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Received",
    Value: 23,
  },
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Verified",
    Value: 4,
  },
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Drawing Preparing ",
    Value: 24,
  },
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Drawing Issuance",
    Value: 25,
  },
  {
    disabled: false,
    group: null,
    selected: false,
    Text: "Drawing Issued ",
    Value: 26,
  },
];

const structuralDetailInfo = [
  {
    structuralEngineer: {
      OwnerName: "Engr. Ahmed Khan",
      ContactNumber: "+92-300-1234567",
      Email: "ahmed.khan@example.com",
      Address: "123 Bahria Town, Islamabad, Pakistan",
      Attachment: [
        {
          name: "Structural_ID_Card.jpg",
          preview: "blob:http://localhost:3000/abc123-structural-preview",
          type: "image/jpeg",
          file: new File([""], "Structural_ID_Card.jpg", {
            type: "image/jpeg",
          }),
        },
      ],
    },
    mepEngineer: {
      OwnerName: "Engr. Sarah Malik",
      ContactNumber: "+92-321-9876543",
      Email: "sarah.malik@example.com",
      Address: "456 DHA Phase 6, Lahore, Pakistan",
      Attachment: [
        {
          name: "MEP_License_Certificate.jpg",
          preview: "blob:http://localhost:3000/xyz456-mep-preview",
          type: "image/jpeg",
          file: new File([""], "MEP_License_Certificate.jpg", {
            type: "image/jpeg",
          }),
        },
        {
          name: "MEP_ID_Card.jpg",
          preview: "blob:http://localhost:3000/xyz456-mep-preview2",
          type: "image/jpeg",
          file: new File([""], "MEP_ID_Card.jpg", {
            type: "image/jpeg",
          }),
        },
      ],
    },
  },
];

export {
  UploadedDocmentModel,
  structuralWorkInfo,
  structuralDetailInfo,
  structuralStatus,
  plotapprovel,
  LDAStatus,
  issuancedrawing,
  preparedrawing,
};
